Add support for optional README path flag to list and track parts used in README file.
ubuntu/desktop-snaps pull request #840
Opened 2024-12-23 09:25 UTC by rudra-iitm

This update introduces a new `--readme-path` argument that allows users to specify the file path to the `README` (or any Markdown file) where the parts used in a YAML file (such as snapcraft or rockcraft) will be listed (with their updated versions).

**Key Changes**:
- New Argument: The `--readme-path` argument is added to specify the path to the target README file.

**Usage**:
- Users can now provide the path to the README file using the `--readme-path` flag. For example:
  ```sh
   --readme-path: 'path/to/readme/file'
   ```
 - User need to comment this in specified README file
   ```
   

   
   ```
 
This will automatically list the parts (with their updated version) used in the YAML file within the specified Markdown file, as demonstrated in the image below.
<img width="899" alt="Screenshot 2024-12-23 at 11 01 24 AM" src="https://github.com/user-attachments/assets/7c48347b-3d47-4a20-93fc-8ea245d95319" />

2024-12-23 09:37 UTC, rudra-iitm commented
@sergio-costas Could you please review this PR? Regarding the test failures, the unittests are still passing locally, but they seem to fail in the workflow due to a 403 status code error. This might be caused by rate limiting on the GitHub API.

2025-01-07 12:29 UTC, sergio-costas requested changes
Some little details.

2025-01-07 12:29 UTC, sergio-costas commented on updatesnap/updatesnapyaml.py
> +        updated_readme = re.sub(
Maybe a check for the existence of the tags would be a good idea. That allows to ensure that they are correct (a typo would result in the data not being updated).

2025-01-07 12:29 UTC, sergio-costas commented on updatesnap/updatesnapyaml.py
> +                        help='Path of the README file parts will be listed.')
I think a better text would be "Path to the README.md file where the parts and their version will be listed.".

2025-01-07 16:23 UTC, rudra-iitm commented on updatesnap/updatesnapyaml.py
> +        updated_readme = re.sub(
Why do we need to check for the existence of a tag? The included components are defined in the `snapcraft.yaml` file, not determined by the user. If there is any typo, it will automatically be corrected in the next workflow run as defined in the `snapcraft.yaml` file.

2025-01-07 16:25 UTC, rudra-iitm commented on updatesnap/updatesnapyaml.py
> +                        help='Path of the README file parts will be listed.')
Done

2025-01-07 16:28 UTC, sergio-costas requested changes

2025-01-07 16:28 UTC, sergio-costas commented on updatesnap/updatesnapyaml.py
> +        updated_readme = re.sub(
I mean: if the user specifies a README file, do check in that README if the `<!-- Begin Included Components -->` and `<!-- End Included Components -->` tags are specified in it.

2025-01-07 17:30 UTC, rudra-iitm commented on updatesnap/updatesnapyaml.py
> +        updated_readme = re.sub(
Done

2025-01-07 19:13 UTC, sergio-costas approved these changes
LGTM.

2025-01-07 19:14 UTC, merged